spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/payment_db
    username: payment_user
    password: payment_password

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/