apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: spring-profile
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: config-server-url
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: eureka-client-url
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: eureka-server-url
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/notification_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: postgres-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: postres-port
            - name: DB_NAME
              value: "notification_db"
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: kafka-bootstrap
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: kafka-bootstrap
            - name: SERVER_PORT
              value: "8086"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
