spring:
  datasource:
    url: jdbc:postgresql://postgres:5433/catalog_db
    username: postgres
    password: admin_password_123
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:29092
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/