spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:eureka-server}
    prefer-ip-address: true
    ip-address: ${EUREKA_IP_ADDRESS:127.0.0.1}
    non-secure-port: ${server.port}
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION:true}
    eviction-interval-timer-in-ms: 60000

# Docker networking configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    com.ecommerce.eureka: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

# High Availability Docker Configuration
---
spring:
  config:
    activate:
      on-profile: docker-ha-peer1

eureka:
  instance:
    hostname: eureka-peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-peer2:8762/eureka/

server:
  port: 8761

---
spring:
  config:
    activate:
      on-profile: docker-ha-peer2

eureka:
  instance:
    hostname: eureka-peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-peer1:8761/eureka/

server:
  port: 8762