spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:https://github.com/your-org/config-repo.git}
          username: ${GIT_USERNAME:}
          password: ${GIT_PASSWORD:}
        native:
          search-locations: file:/config-repo/
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

logging:
  file:
    name: /var/log/config-server.log